# Generated by Django 5.2.4 on 2026-04-17 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('autho', models.CharField(max_length=50)),
                ('isbn', models.CharField(max_length=10)),
                ('pubdate', models.DateField()),
                ('pricestandard', models.IntegerField()),
                ('adult', models.BooleanField()),
                ('salespoint', models.IntegerField()),
                ('publisher', models.CharField(max_length=50)),
            ],
        ),
    ]
