# Generated by Django 5.2.4 on 2026-04-15 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garage',
            old_name='is_parking_avaliable',
            new_name='is_parking_available',
        ),
    ]
